### PR TITLE
Checked details of all SPs and fixed a few minor details

### LINKED ISSUE #5: GSSP records not updated in the ttl files
I took a look of the ISC2018 and ISC 2020 versions of the ttl files. Seems some golden spike information is missing. 

In 2018-08 version of the ISC chart, there are 72 golden spikes. In the corresponding ttl file I can find 64. 

In the 2020 version of the ISC chart there are 74 golden spikes. In the corresponding ttl file I can find 66.  

Also in some place the golden spike attributes are incorrect. Such as geo:hasGeometry isc:BaseMiddleOrdovician-location in the below:
```
isc:BaseMeghalayanSP
  a gts:StratigraphicPoint ;
  dct:source "International Commission on Stratigraphy - Formal subdivision of the Holocene Series/Epoch"@en ;
  gts:ratifiedGSSP true ;
  gts:status "Ratified 2018-06-26"@en ;
  geo:hasGeometry isc:BaseMiddleOrdovician-location ;
  rdfs:comment "Mawmluh Cave speleothem, Meghalaya, India."@en ;
  rdfs:label "Stratotype Point Base of Meghalayan"@en ;
  rdfs:seeAlso <http://stratigraphy.org/index.php/ics-news-and-meetings/125-formal-subdivision-of-the-holocene-series-epoch> ;
  rdfs:seeAlso <http://www.stratigraphy.org/GSSP/index.html> ;
  skos:prefLabel "Stratotype Point Base of Meghalayan"@en ;
.
```

And  time:numericPosition "4200"^^xsd:decimal in the below:

```
isc:BaseMeghalayanTime
  a time:TimePosition ;
  time:hasTRS <http://resource.geosciml.org/classifier/cgi/geologicage/bp> ;
  time:numericPosition "4200"^^xsd:decimal ;
```

### PR DESCRIPTION
**Pull request by dr-shorthair**
I have checked all the boundaries - there are no missing SPs. 
Added 4 locations - there are a few missing locations for ratified SPs because they are missing in the sources that I'm using - https://timescalefoundation.org/gssp/index.php today. 
I have not cross-checked against  https://stratigraphy.org/gssps/ yet. 

Set ratified flag for all SPs, not only 'true'
Checked all the boundary levels and correlations events. 
Added some links to the figures from https://timescalefoundation.org/gssp/index.php 

I think this fixes #5 - OK @xgmachina  ?

### CODE REVIEW

**Comment by dr-shorthair** [comment]
TODO: cross-check against https://stratigraphy.org/gssps/ 
Could @arademaker or @xgmachina do the cross-check?

**Comment by alexandretessarollo** [comment]
For the Albian SP the original
https://github.com/CGI-IUGS/timescale-data/blob/3252bbef3bc4ed21a607134daf51ef9602097919/rdf/isc2020.ttl#L786
matches [https://stratigraphy.org/gssps/](https://stratigraphy.org/gssps/) while the proposed commit
https://github.com/CGI-IUGS/timescale-data/blob/319c8c43df8600537da66af53eefe936a18ee9de/rdf/isc2020.ttl#L795
matches [https://timescalefoundation.org/gssp/index.php?parentid=all](https://timescalefoundation.org/gssp/index.php?parentid=all).

The cross-check (for these lines at least) checks, but I believe we need to set some ground rules on how to proceed when a reference supersedes another one. I extended this point in #3 , contributions are welcome.

**Review by xgmachina — COMMENTED** [review]
A few days ago I was checking the 2018-08 version of your vocabulary. And now for the 2020 version I was thinking that there could be 10 SPs that need a check in the ttl code: Meghalayan, Northgrippian, Chibanian, Chattian, Albian, Hauterivian, Toarcian, Sakmarian, Gorstian, Miaolingian. Some of them may already have complete information. But just in case please take a look of all. Also for a few SPs I think the latest attributes are not released from the stratigraphy community yet.

**Comment by xgmachina** [comment]
Hi @dr-shorthair I load your updated v2020 vocabulary in a graph on my triple store http://virtuoso.nkn.uidaho.edu:8890/sparql/ and run a query below. It shows you may need to update the boundary time of a few concepts. See those at the bottom of the SPARQL result. 


```
prefix dc: <http://purl.org/dc/elements/1.1/>
prefix gts: <http://resource.geosciml.org/ontology/timescale/gts#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix time: <http://www.w3.org/2006/time#>
prefix ts: <http://resource.geosciml.org/vocabulary/timescale/> 
prefix isc: <http://resource.geosciml.org/classifier/ics/ischart/> 
prefix samfl: <http://def.seegrid.csiro.au/ontology/om/sam-lite#> 
prefix geo: <http://www.opengis.net/ont/geosparql#>

SELECT DISTINCT  ?baseSp 
WHERE
{
                
   GRAPH <http://deeptimekb.org/isc2020new>
   {   
       ?bdry  a gts:GeochronologicBoundary ;
              time:inTemporalPosition ?baseTime ;
              gts:stratotype ?baseSp .
        
        ?baseTime time:numericPosition ?baseTimeNum . 
        
       ?baseSp 
               # geo:hasGeometry ?spLocation ;  
               rdfs:label ?spLabel ;
               gts:ratifiedGSSP ?tf . 
        FILTER(regex(str(?tf), "true", "i"))

      # ?spLocation geo:asWKT ?spCoordinates .
   }

}
ORDER BY ?baseTimeNum
```

**Comment by dr-shorthair** [comment]
Those use a different scale - <http://resource.geosciml.org/classifier/cgi/geologicage/bp> rather than <http://resource.geosciml.org/classifier/cgi/geologicage/ma>

Need to look at `time:hasTRS` alongside the `time:numericPosition`

Always check the units-of-measure!

**Comment by dr-shorthair** [comment]
It might be easier on the user if the whole dataset used a single TRS. 
I switched to bp for the younger ones because they overlap into the archeological eras where the datum (1950) and units (years) begins to matter. 

Another option would be to have two `time:inTemporalPosition` properties for these boundaries - one in ma, the other in bp. Then the query could select a set with a uniform TRS. How would that work for you?

**Comment by dr-shorthair** [comment]
BTW - the FILTER expression can be direct - you don't have to do a string comparison on a boolean. 

```sparql
SELECT * 
WHERE
{
                
       ?bdry  a gts:GeochronologicBoundary ;
              time:inTemporalPosition ?baseTime ;
              gts:stratotype ?baseSp .
        
        ?baseTime time:numericPosition ?baseTimeNum ;
            time:hasTRS <http://resource.geosciml.org/classifier/cgi/geologicage/ma> . 
        
       ?baseSp 
               # geo:hasGeometry ?spLocation ;  
               rdfs:label ?spLabel ;
               gts:ratifiedGSSP ?tf . 
        FILTER(?tf)

      # ?spLocation geo:asWKT ?spCoordinates .

}
ORDER BY ?baseTimeNum
```

**Comment by xgmachina** [comment]
> It might be easier on the user if the whole dataset used a single TRS.
> I switched to bp for the younger ones because they overlap into the archeological eras where the datum (1950) and units (years) begins to matter.
> 
> Another option would be to have two `time:inTemporalPosition` properties for these boundaries - one in ma, the other in bp. Then the query could select a set with a uniform TRS. How would that work for you?

Using two TRSs would be a better solution from the user's point of view - no need to modify the query code.

**Pull request merged**
